### PR TITLE
GeoProjection: Fix the handling of left handed Unreal location values

### LINKED ISSUE #9389: Carla GPS location mismatch for Carla 0.9.15 and 0.9.16
**Setup**
Describe the setup you are using to run CARLA along with its version:
  * CARLA version: 0.9.16
  * Platform: linux
  * Python version: 3.11
  * GPU: RTX A1000
  * GPU Drivers: CUDA12

**Describe the bug**
I am using bench2drive leaderboard. For exactly the same code, the Carla 0.9.15 get gps location at 'gps': (8909, array([ 0.00293298,  0.00160249, -0.05002071])), while  Carla 0.9.16 get the gps location at 'gps': 'gps': (12397, array([-0.00293595,  0.00160185, -0.05002071])). The actual game time at this frame is exactly the same. There is a plus minus sign difference of the first axis in the gps data. Can we fix this bug?

**Steps to reproduce**
Just run simlingo repo code on two 0.9.15 and 0.9.16 version of Carla can produce this problem. https://github.com/RenzKa/simlingo

### LINKED ISSUE #9530: CRITICAL❗Incorrect geocoordinates and wrong north orientation in Digital Twin map generation (9.16 - ue4-dev branch)
Setup
CARLA version: 0.9.16 (Digital Twin Map Generator)
Branch: ue4-dev
Platform: Ubuntu Linux 20.04 / 22.04
Python version: 3.8 / 3.10
GPU: NVIDIA (e.g. RTX / GTX)
GPU Drivers: NVIDIA proprietary drivers (e.g. 535.xx)

In the ue4-dev branch, the geocoordinates generated in the CARLA Digital Twin map are incorrect and the map is not oriented with the correct geographic north.

After importing real-world geographic data (e.g. IGN data, WGS84, or projected coordinate systems such as Lambert93), the resulting CARLA map shows a significant mismatch between real-world positions and CARLA coordinates.
Additionally, the map orientation is rotated: real north does not correspond to CARLA north, leading to axes misalignment (e.g. real north appears as west or south in CARLA).

This prevents accurate alignment of real GPS trajectories or satellite imagery with the CARLA simulation.

Steps to reproduce

Use the Digital Twin Map Generator from the ue4-dev branch.
Generate a map from real-world geographic data (IGN / WGS84 / projected CRS).
Define the <geoReference> in the generated OpenDRIVE file.
Load the map into CARLA.
Compare known real-world GPS points or satellite imagery with CARLA actor positions.
Observe position offsets and incorrect north orientation.

Expected behavior

Generated CARLA maps should correctly match real-world geocoordinates.
CARLA north should be aligned with true geographic north.
GPS trajectories converted from WGS84 or projected CRS should overlay correctly on the CARLA map without rotation or offset.

### PR DESCRIPTION
**Pull request by berndgassmann**
Use a helper class LocationRightHanded to allow the implemenation of the GeoProjections to perform their projections in a right handed coordinate frame.

The explicit handling using LocationRightHanded revealed error in OffsetTransform: result Location is now transformed back to Unreal coordinates and Rotation is fixed.

Allow OpenDRIVE offsets for any type of projection

Fix UniversalTransverseMercatorParams::operator!=()

This fix should contain the fixes which #9552 tried to tackle by using a more general solution. Especially this solution only applies the left-handed/right-handed conversion to the carla::geom::Location values, because all offset values provided by the OpenDRIVE map itself have to be considered to be in right-handed notation. 

#### Description

Fixes #9530
Fixes #9389
And implements #9552 in a more complete manner.

   

#### Where has this been tested?

  * **Platform(s):** ... Ubunut 24.04
  * **Python version(s):** ...3.12.
  * **Unreal Engine version(s):** ... 4.26

#### Possible Drawbacks

- - -
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/9590)

### CODE REVIEW

File: PythonAPI/carla/source/libcarla/Geom.cpp [hunk 1]
```diff
@@ -359,21 +381,64 @@ void export_geom() {
 
   class_<cg::WebMercatorParams>("GeoProjectionWebMerc")
     .def(init<cg::Ellipsoid>((arg("ellps")=cg::Ellipsoid())))
```
Comment (glopezdiest) [inline PythonAPI/carla/source/libcarla/Geom.cpp]: [Applied to all projections]

There are two inits, one with the offset transfom and one without it. I'd merge them into one.

File: PythonAPI/carla/source/libcarla/Geom.cpp [hunk 2]
```diff
@@ -359,21 +381,64 @@ void export_geom() {
...
+    .def(init<cg::Ellipsoid, boost::optional<cg::OffsetTransform>>((arg("ellps")=cg::Ellipsoid(), arg("offset")=boost::python::object())))
     .def_readwrite("ellps", &cg::WebMercatorParams::ellps)
+    .add_property("offset",
```
Comment (glopezdiest) [inline PythonAPI/carla/source/libcarla/Geom.cpp]: [Applied to all projections]

Is this really the best way to define the offset? It feels convoluted. Why not just pass the default offset? Or None? 

And if that isn't possible, at least try to merge the four offsets into one template to avoid repeated code

**Comment by glopezdiest** [comment]
Hey @berndgassmann, thank you for the PR. The implementation is correct, and it fixes the issue with the offset transform.

I've left some comments regarding the exposure to the PythonAPI. The code itself works fine but It'd be great if a couple of things were changed.

**Comment by berndgassmann** [comment]
Sure I can change...
did you click on publishing of the comments yet?
:-)

**Comment by glopezdiest** [comment]
There, I though I had published them, sorry

File: PythonAPI/carla/source/libcarla/Geom.cpp (hunk 1 above)
Comment (berndgassmann) [reply PythonAPI/carla/source/libcarla/Geom.cpp]: Now reduced to one single init. Had to refactor the boost optional handling to make the default parameter as well as the read/write access working.

File: PythonAPI/carla/source/libcarla/Geom.cpp (hunk 2 above)
Comment (berndgassmann) [reply PythonAPI/carla/source/libcarla/Geom.cpp]: Now the code duplication is gone and delegated to some general template functions OptionalFromPythonConverter, OptionalToPythonConverter that can be used for other boost optional python access.

**Review by Blyron — APPROVED** [review]
