### PR TITLE
Client side improvements

### LINKED ISSUE #767: Deadlock when closing the simulator while a client is connected
To reproduce:

1) Launch the simulator (game or editor)
2) Connect a client
3) Stop the simulation

Version 0.9.0 at least both Linux and Windows.

My bet goes to this piece of code where the future.get() may block forever
https://github.com/carla-simulator/carla/blob/a1684ad0ae52344b23eaf0358ed9f40fe845f898/LibCarla/source/carla/rpc/Server.h#L59-L61

### LINKED ISSUE #809: Relase GIL at python API boundaries
From the looks of it the boost python (new) layer is not releasing the GIL for python.

This makes having a responsive UI (using pyglet or pygame) pretty hard to accomplish (especially say when a timeout to the carla server happens).

An easy way to test this is to setup a server, then try to run a client, then after the client connects, kill the server and the app will usually freeze up.

Something like https://stackoverflow.com/a/41168814 is probably needed...

### LINKED ISSUE #843: Streaming client keeps trying to reconnect after destroying a sensor
When you subscribe to a sensor stream from the client side, a new "streaming client" is created that listens to any data generated by that sensor, on disconnect this client continuously tries to reconnect failing to read data if the sensor was destroyed.

To reproduce, just create a sensor from the client side, set the listen callback, and destroy the sensor. It starts printing warnings from that point on.

### PR DESCRIPTION
**Pull request by nsubiron**
#### Description

Requires #829 and all its dependencies.

Includes a bunch of different improvements to the client-side code:

- Related to #810, C++ API has been refactored, hopefully easier to use now, although it still needs to be polished to be linkable to other apps but it's a step forward.
- Fix #809, release GIL whenever possible (this has really improved performance of the Python API, thanks @harlowja for reporting!).
- Make possible to unsubscribe from a sensor (in Python sensors now have a `stop()` method).
- Fix #843 Streaming client keeps trying to reconnect after destroying a sensor.
- Fix #767 Deadlock when closing the simulator while a client is connected (or at least one of them).
- Fix crash on simulator shutdown if a client has connected at some point.
- Related to #784, vehicle control and set transform methods are now sent async which greatly improves performance in the client-side (we still want to add batch mode though).
- Vehicle control is cached and not sent if haven't changed. Now it's possible to call `vehicle.apply_control(...)` continuously and the message will only be sent when necessary.

Plus I redesigned the Python examples:

- `example.py` is gone, now there is a `tutorial.py` in which a simple example on how to use the API is commented step by step.
- `manual_control.py`now has a fancy user interface (for Carla standards :wink:), and in general the driving experience should be smoother. Although you still depend on a simulator running fast, the input is captured at a decent frame rate. It is also possible to change the main view between the different cameras available.

#### Where has this been tested?

  * **Platform(s):** Ubuntu 16.04
  * **Python version(s):** 2.7

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/856)

### CODE REVIEW

**Comment by harlowja** [comment]
Awesome, will look at soon :)

File: LibCarla/source/carla/NonCopyable.h [hunk 1]
```diff
@@ -8,15 +8,30 @@
 
 namespace carla {
 
-  /// Inherit (privately) to suppress copy-construction and copy-assignment.
+  /// Inherit (privately) to suppress copy/move construction and assignment.
```
Comment (harlowja) [inline LibCarla/source/carla/NonCopyable.h]: Why not just use https://www.boost.org/doc/libs/1_63_0/libs/core/doc/html/core/noncopyable.html ?

File: LibCarla/source/carla/client/Client.h [hunk 2]
```diff
@@ -6,29 +6,13 @@
 
 #pragma once
```
Comment (harlowja) [inline LibCarla/source/carla/client/Client.h]: What about having a client that just follows https://en.cppreference.com/w/cpp/language/pimpl

Then there can be a python client and a c++ client 'implemtnation' and all that users of either interact with is the pimpl layer (which makes including the pimpl layer in a project pretty straightfward).

File: LibCarla/source/carla/NonCopyable.h (hunk 1 above)
Comment (nsubiron) [reply LibCarla/source/carla/NonCopyable.h]: Yeah, this comes back from the time we didn't include boost. I just kept using it for consistency, we could alias it here.

File: LibCarla/source/carla/client/Client.h (hunk 2 above)
Comment (nsubiron) [reply LibCarla/source/carla/client/Client.h]: Yes, the pimpl is in the detail::Client, this class is pretty useless by itself, the API depends on all the other classes that are in the "client" folder.

What it would be nice is to have a pure-C interface with the very minimum for communicating with the server, so it would be easier to link anywhere. In practice however the communication is quite complex, a lot of things are cashed to avoid calling the server all the time. It would require some thought doing such interface.

File: LibCarla/source/carla/client/Sensor.cpp [hunk 3]
```diff
@@ -0,0 +1,61 @@
...
+#include "carla/client/Sensor.h"
+
+#include "carla/Logging.h"
+#include "carla/client/detail/Client.h"
+
+namespace carla {
+namespace client {
+
+  Sensor::~Sensor() {
+    if (IsAlive()) {
```
[the remark this answers is not in the document]
Comment (nsubiron) [reply LibCarla/source/carla/client/Sensor.cpp]: True, I'll make sure none of them do.
