### PR TITLE
Fix Low / Epic quality levels transition

### LINKED ISSUE #2336: Low-quality mode is extremely bright
When running in low quality mode, there is an exposure problem which makes the game very bright. See screenshot below.

**Epic quality**
image

**Low quality**
image

This happens in 0.9.7 and was not happening in 0.9.6.

It seems to be due to the scalability level for post-process that is set to 0 in low quality:
```
sg.PostProcessQuality=0
```
More specifically, it's this specific value that causes the problem:
```
r.EyeAdaptationQuality=0
```
(as defined in `[PostProcessQuality@0]` of BaseScalability.ini).

Switching `r.EyeAdaptationQuality` to 1 or 2 solves the problem.

We also found out that using the apparently new `BP_WeatherSafe` as weather class instead of `BP_Weather` prevents the problem to occur.

This problem occurs on both Windows and Linux (Ubuntu 18.04). GPUs tested include nVidia 1070 and 2070.

### PR DESCRIPTION
**Pull request by bernatx**
#### Description

This PR will fix the transition from Epic / Low quality settings. 

Two problems were found in version Carla 0.9.7:

First, Unreal was writing the last quality settings to a file in /Saved/ folder and was reading and applying those settings without taking care of the desired quality settings that the user could specify.
We have fixed this thanks to the help of BenAscent who pointed the way to disable the writing of those settings.

Second, when enabling low-quality settings, the autoexposure was disabled but a value of Exposure Compensation of 4.5 was applied what made the image brighter than usual. We fixed that forcing autoexposure to be enabled also at low-quality level.

Fixes #2336, #2335

#### Where has this been tested?

  * **Platform(s):** Ubuntu and Windows
  * **Python version(s):** 3.7
  * **Unreal Engine version(s):** 4.22

#### Possible Drawbacks

If you had the problem of bright image in low-quality settings, probably you will need to remove the /Saved/ folder because there Unreal has written the last quality settings. Just clean that folder and run again with any Epic or Low quality settings.

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/2352)

### CODE REVIEW

**Comment by jeffreykxiao** [comment]
This change seems to work fine for me (Ubuntu and Windows). One thing that I think should be mentioned is that the location of the saved config on Linux was in my user directory under `.config` or something similar to this.

File: Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Settings/CarlaSettingsDelegate.cpp [hunk 1]
```diff
@@ -159,13 +165,17 @@ void UCarlaSettingsDelegate::CheckCarlaSettings(UWorld *world)
 
 void UCarlaSettingsDelegate::LaunchLowQualityCommands(UWorld *world) const
 {
+  if (!world)
+  {
+    return;
+  }
+
```
Comment (jeffreykxiao) [inline Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Settings/CarlaSettingsDelegate.cpp]: Thanks for adding this! Not sure under what circumstances it would get popped, but I definitely appreciate that the function implementations are now consistent with each other.

Comment (bernatx) [reply Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Settings/CarlaSettingsDelegate.cpp]: Yes, I think it is more consistent that way. Thanks.

**Comment by marcgpuig** [comment]
@jeffreykxiao looks like you are blocking the PR, can you accept it?

**Comment by bernatx** [comment]
I think jeffreykxiao needs to resolve a discussion yet. Can you check further? The PR is still blocked.

**Comment by jeffreykxiao** [comment]
> I think jeffreykxiao needs to resolve a discussion yet. Can you check further? The PR is still blocked.

Should be good now - I didn't realize that I needed to review in Reviewable and not github. 🙇

**Comment by exoticDFT** [comment]
> @jeffreykxiao Indeed!
> I had to remove `rm -rf ~/.config/Epic/CarlaUE4/Saved` to make it work again (Ubuntu 18.04).
> I think it will be worth mentioning this somewhere in our docs.
> 
> > Reviewed 2 of 2 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/2352#-:-LyZ9aVG9CxSDH5N4-IT:b-li6b1k)_ status: all files reviewed, 1 unresolved discussion (waiting on @bernatx)

@marcgpuig As a word of caution, this suggestion may be overkill. Specifically for those that stored some previous recordings made in Carla. The only file that needs to be removed in this folder is `~/.config/Epic/CarlaUE4/Saved/Config/LinuxNoEditor/GameUserSettings.ini`. This is the file that stores previously saved configuration for the settings mentioned in these issues.

**Comment by marcgpuig** [comment]
@exoticDFT Indeed, the docs have been correctly updated (not uploaded yet) with this specific information and I've updated my comment to avoid problems to other users. Thanks for pointing it out!

**Comment by exoticDFT** [comment]
@marcgpuig Great to hear it's already in the next documentation update! Glad I could help.
