### PR TITLE
Fixes std::numeric_limits<float>::epsilon error

### LINKED ISSUE #3012: Carla 0.9.9 crashing way more than previous version
Hello, I am doing Reinforcement Learning in CARLA for more than a year and I have always encountered issues with CARLA crashing time to time (with a Segmentation Fault as mentionned in #1627 or #1227). But generally this was happening really rarely. Usually I have 5/6 instance of CARLA running independently during around 4/5 days and sometimes one of this instance of CARLA would crash and I had to relaunch it.

I recently moved from CARLA 0.9.6 to CARLA 0.9.9 and I discovered that the crashs were happening much more, basically I have trouble to run a CARLA for more than a day without crash. Particularly my script (a slight modification to the spawn_npc.py script) spawning/deleting/respawning all the surrounding autopilot vehicles and pedestrians seems really unstable throwing this exception many time:
***$ what(): length > 2.0f * std::numeric_limits<float>::epsilon()***
***Segmentation fault (core dumped)***

As in the script spawn_npc.py I set the traffic manager with those commands:
***
$ traffic_manager.set_global_distance_to_leading_vehicle(2.0)
$ traffic_manager.set_hybrid_physics_mode(True)
***

### PR DESCRIPTION
**Pull request by jackbart94**
#### Description

Removes usage of ``MakeUnitVector`` by using ``MakeSafeUnitVector`` and fixes the std::numeric_limits<float>::epsilon error

Fixes #3012

#### Where has this been tested?

  * **Platform(s):** Ubuntu 18
  * **Python version(s):** 3.6
  * **Unreal Engine version(s):** 4.24

#### Possible Drawbacks

None

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3243)

### CODE REVIEW

**Review by pravinblaze — APPROVED** [review]
MakeSafeUnitVector is definitely better to use in cases where we can have a zero magnitude input vector.
Thanks for finding the unguarded usage of MakeUnitVector and replacing it with MakeSafeUnitVector.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/3243#-:-MGNhFIe3WP3nEWnxtGH:b-khno1c)* status: :shipit: complete! all files reviewed, all discussions resolved

File: LibCarla/source/carla/trafficmanager/Constants.h [hunk 1]
```diff
@@ -78,6 +78,7 @@ static const float MAX_LOCKING_EXTENSION = 10.0f;
 static const float WALKER_TIME_EXTENSION = 1.5f;
 static const float SQUARE_ROOT_OF_TWO = 1.414f;
 static const float VERTICAL_OVERLAP_THRESHOLD = 4.0f;
+static const float EPSILON = 2.0f * std::numeric_limits<float>::epsilon();
```
Comment (ThrashAbaddon) [inline LibCarla/source/carla/trafficmanager/Constants.h:81]: constexpr

File: LibCarla/source/carla/trafficmanager/LocalizationUtils.cpp [hunk 2]
```diff
@@ -5,16 +5,19 @@
...
 
+using constants::Collision::EPSILON;
+
 float DeviationCrossProduct(const cg::Location &reference_location,
                             const cg::Vector3D &heading_vector,
                             const cg::Location &target_location) {
   cg::Vector3D next_vector = target_location - reference_location;
-  float vector_magnitude_epsilon = 2.0f * std::numeric_limits<float>::epsilon();
-  next_vector = next_vector.MakeSafeUnitVector(vector_magnitude_epsilon);
+  next_vector = next_vector.MakeSafeUnitVector(EPSILON);
```
Comment (ThrashAbaddon) [inline LibCarla/source/carla/trafficmanager/LocalizationUtils.cpp:20]: As you  are passing always `EPSILON` maybe make it a default on `MakeSafeUnitVector` ?
